### ISSUE TITLE
Ancestries doesn't work with the Item Table module

### ISSUE THREAD

**Issue by mrcomac** [kristianserrano/savage-eberron-for-foundry-vtt#3]
I'm getting the warning below and not sure if this module needs an update or the item table needs that update.

```
foundry-esm.js:4621 Error: The ancestry ability type has been deprecated in favor of the new ancestry Item
Deprecated since Version 4.1
Backwards-compatible support will be removed in Version 5.0
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Object.get [as ANCESTRY] (swade.ts:73:21)
    at ItemTables.getData (ItemTables.mjs:243:109)
    at async ItemTables._render (foundry.js:5838:18)
    at async ItemTables._render (foundry.js:6572:5)
    at async ItemTables._render (ItemTables.mjs:143:9)
```

When I try to drag and drop the ancestries to the Char in the Create Character, it doesn't work as well (but it doesn't work for the swade core rules module as well, maybe something related to item tables and the new ancrestry item).

**Comment by kristianserrano** [comment]
Yes, both are related and unrelated. The warning you included is just a deprecation warning, not an actual error. The issue with ancestries not being droppable is because of that change. The script was looking for an ability Item with the ancestry subtype rather than an ancestry Item. I have a fix in my local files that I plan to push shortly.

Bonus: I'm adding ability costs and ancestry values to the tables as well.

**Comment by mrcomac** [comment]
do you need to migrate those item within the eberron's compendium to this new item as well?

**Comment by kristianserrano** [comment]
Not so much migrate as update. I'm in the process of updating the ancestries' abilities with costs. (I spent some time on it yesterday only to find a bug in the tweaks form that prevents the values from actually being stored. I fixed the bug on my own copy of the system, but I'll have to go back and do it again now that the values will stick.

I'm also taking the opportunity to fix up and optimize a few of the ancestries, like using choice sets for the Half-elf rather than having two versions of it or making better use of mutations to customize the descriptions of ancestral abilities.
